### ISSUE TITLE
audio_processor.py bug

### ISSUE THREAD

**Issue by dojochu** [keunwoochoi/music-auto_tagging-keras#11]
In `compute_melgram()` function, just need to make sure you provide integer values for the indices

Adapt Line 31:
`src = src[(n_sample - n_sample_fit) / 2:(n_sample + n_sample_fit) / 2]`

To:
`src = src[int((n_sample - n_sample_fit) / 2):(int(n_sample + n_sample_fit) / 2)]`

**Comment by keunwoochoi** [comment]
I think both `n_sample` and `n_sample_fit` are always integers.
