### ISSUE TITLE
Wrong Prediction with GTZAN Music Genre Dataset 

### ISSUE THREAD

**Issue by srinidhikrs** [keunwoochoi/music-auto_tagging-keras#12]
Hi,

I downloaded GTZAN Music genre dataset from http://marsyasweb.appspot.com/download/data_sets/?_sm_au_=i7HSSSWqdVMd13T7.
I converted the GTZAN dataset from 22050hz to 12000 hz sampling rate using sox. (ex: sox inputfile.wav -b16 -r12000 out.wav)
When I ran the example tagging script with audio files from GTZAN/rock directory, most of the predictions are showing it as jazz.
What am I doing wrong?

regards
Srinidhi

**Comment by keunwoochoi** [comment]
I'd recommend you to use it as a feature extractor and add a classifier on the top of it, rather than use the result as it is.
