### ISSUE TITLE
Can't run any of models with the latest python packages

### ISSUE THREAD

**Issue by nartes** [keunwoochoi/music-auto_tagging-keras#21]
https://gist.github.com/anonymous/062721cae29f62ab7262ceb1d0e66a59 - stack trace
https://gist.github.com/anonymous/cfb146880d54675b213e125b1624f313 - requirements.txt
https://gist.github.com/anonymous/b30226c691a3d2bd7999b67356dd5461 - keras.conf

I tried both backends - Theano and Tensorflow.

Could you provide your requirements.txt?

I'm using only CPU.

**Comment by nartes** [comment]
Tensorflow backend can't load model's weights.
https://gist.github.com/anonymous/595a4b0670bf0e00410d471ced923166

**Comment by keunwoochoi** [comment]
Thanks for interest. I am considering removing `MusicTaggerCNN/CRNN` and replace them with [compact_cnn](https://github.com/keunwoochoi/music-auto_tagging-keras/tree/master/compact_cnn) which runs with latest python packages. Could this help you at least for temporary?

**Comment by nartes** [comment]
Glad to get your reply, Keunwoo!

I just tried to run your implemtation before digging deeper. I need to read your paper, since I don't know what compact_cnn is.
Actually I am interested in one of bibliography references from the paper. (https://arxiv.org/abs/1508.01774) I've not found the code for that one, and by chance discovered yours.
So I need to learn tensorflow, before that I was playing around with MATLAB only.

**Comment by keunwoochoi** [comment]
Yeah.. I'd guess cnn/crnn structure for tagging is simpler and more straightforward than those for transcription, just because of the natures of tasks. Numpy/keras/tf is not too hard for ex-MATLAB users!
