### ISSUE TITLE
Keras 2.0

### ISSUE THREAD

**Issue by lvaleriu** [keunwoochoi/music-auto_tagging-keras#25]
Are the CompactCnn weights compatible with the last version of keras?

**Comment by keunwoochoi** [comment]
No, as written in README, use keras 1.1 or 1.2, nothing else but BN has changed in keras 2.0.

**Comment by lvaleriu** [comment]
Could it be possible to train the Compact CNN again with keras 2.0? I can do it myself if you dont have time.

**Comment by keunwoochoi** [comment]
Thinking of doing it at some point, not right away though. There seems some model loading issue in Keras 2.0 and kinda waiting till it becomes mote stable.
