### ISSUE TITLE
Compact cnn training precision

### ISSUE THREAD

**Issue by lvaleriu** [keunwoochoi/music-auto_tagging-keras#28]
On what dataset did you train the compact_cnn model? I thought it was this one https://labrosa.ee.columbia.edu/millionsong but then I'm seeing that the network accepts raw audio data in the input. The millionsong dataset only contains extracted audio features.

Thanks!

**Comment by keunwoochoi** [comment]
Yep I have a set of crawled audio files.

**Comment by lvaleriu** [comment]
How many? 10k, 100k?

**Comment by keunwoochoi** [comment]
about 990k I think.

**Comment by lvaleriu** [comment]
You have crawled about 990K songs. That's big! Full samples or just 29 seconds preview?

**Comment by keunwoochoi** [comment]
30-60 seconds. .... and *I* didn't do it, I just got to get it..

**Comment by lvaleriu** [comment]
Private source?

**Comment by keunwoochoi** [comment]
Yup.
Please email me, gnuchoi@gmail.com and please delete this issue ;) thanks.

**Comment by lvaleriu** [comment]
Ok. Will delete it right away
