### ISSUE TITLE
Preview Audio files for training

### ISSUE THREAD

**Issue by techscientist** [keunwoochoi/music-auto_tagging-keras#29]
Hi @keunwoochoi ! Great work on this repo! Seriously amazing.

I was just wondering how it is possible to get the short preview clips for the tracks in the MSD. I know that, in one of your repos, you stated that there are currently only 2 options: crawling the web or "crawling your colleagues"

But I just wanted to ask, do you know some place where I can get them, so that I can retrain the network on my own. If I am not mistaken, I need the preview clips to retrain the network, right? (The 7Digital API recommended by MSD to get the preview audio files is not working, so I do no know how to "scrape" the preview files from the internet? How were you able to get access to the preview audio files?

Thanks!

**Comment by keunwoochoi** [comment]
Hi, could you please email me? Thanks.

**Comment by techscientist** [comment]
Hi @keunwoochoi , thanks for your reply. Is your email: gnuchoi+github@gmail.com?

**Comment by keunwoochoi** [comment]
yes. or without the suffix.

**Comment by techscientist** [comment]
@keunwoochoi , as per your suggestion, I have sent you an email. Thanks for taking the time to help!
