### ISSUE TITLE
How to use compact_cnn for tagging?

### ISSUE THREAD

**Issue by AmberLau** [keunwoochoi/music-auto_tagging-keras#30]
Do you have any example about tagging with [compact_cnn](https://github.com/keunwoochoi/music-auto_tagging-keras/tree/master/compact_cnn)?
it seems that your example main.py is for feature extraction

**Comment by keunwoochoi** [comment]
Yes it is for feature extraction. Although it was trained for research on music tagger, I'm afraid it can't be directly deployed as a music tagger for few reasons. One of the reasons is the training data is not balanced, so the prediction is pretty biased.
