### ISSUE TITLE
problem with the model generation

### ISSUE THREAD

**Issue by emmanuelbernieri** [keunwoochoi/music-auto_tagging-keras#31]
when I run the example_tagging an error occurs in the MusicTaggerCNN: 

ValueError: Dimension 0 in both shapes must be equal, but are 96 and 1366 for 'Assign' (op: 'Assign') with input shapes: [96], [1366].

How can we solve this problem ? 

Kind regards 

Emmanuel

**Comment by keunwoochoi** [comment]
Could you check #22?

**Comment by emmanuelbernieri** [comment]
Ok I see, 

In that case could you please explain to me on the compact cnn. How do you transform a .wav or .mp3 file into the 1100103.clip.npy ? 

Kind regards

**Comment by keunwoochoi** [comment]
Just pushed an example: 
https://github.com/keunwoochoi/music-auto_tagging-keras/blob/master/compact_cnn/prepare_audio.py . Basically it's decoding, resampling, downmixing, and trimming.

**Comment by emmanuelbernieri** [comment]
it's perfectly working 👍 

thank you very much
