### ISSUE TITLE
the npy for mp3 is not the same with the logamplitude melspectrogram I got using the code audio_processor.py 

### ISSUE THREAD

**Issue by lorashen** [keunwoochoi/music-auto_tagging-keras#40]
I use the code audio_processor.py to get the logamplitude melspectrogram for  
bensound-dubstep.mp3, but find not the same with the array in bensound-dubstep.npy.

Why is this?

**Comment by keunwoochoi** [comment]
hi, probably because something has changed in librosa, but i'm only guessing and have no time looking into it.
