### ISSUE TITLE
what is the 29.1 file of million song?

### ISSUE THREAD

**Issue by loveJasmine** [keunwoochoi/music-auto_tagging-keras#5]
do you refer the subset of one million songs?

**Comment by keunwoochoi** [comment]
did I mention 29.1 files somewhere? It is 29.1 second and they are preview clips of MSD.

**Comment by keunwoochoi** [comment]
Oh, probably you mean those lines from readme. 

More information about the files are [in this repo](https://github.com/keunwoochoi/MSD_split_for_tagging)

**Comment by loveJasmine** [comment]
do you means just 
git clone https://github.com/keunwoochoi/MSD_split_for_tagging under the music-auto_tagging-keras
?

**Comment by keunwoochoi** [comment]
* Where to clone doesn't matter
* I used about 22k songs from MSD
* The repo only contains their ID's and labels, not the audio file or anything else.

**Comment by VanushVaswani** [comment]
I have a question related to this work. I am trying to figure out how to input audio to a CNN. In this work, are all audio clips the same size? Any tips on how to handle variable length audio (i.e, an entire song would be of differing lengths).

**Comment by as641651** [comment]
@keunwoochoi  22k? In the paper, you have mentioned about 214k clips. 
The repository do not contain the clips. So I suppose, you have downloaded the preview clips, trimmed it to 29s and got the mel-spectogram. Right?

**Comment by keunwoochoi** [comment]
@VanushVaswani All audio clips are the same size. There could be some heuristics on how to get the 29s segments and how to merge the scores. E.g., random, middle, structure segmentation, ..

**Comment by keunwoochoi** [comment]
@as641651 Thanks for noting it, you're correct. It's 214k clips. Yes, that's correct.
