### ISSUE TITLE
Reproduce and how to avoid overfitting

### ISSUE THREAD

**Issue by NickCJ83** [keunwoochoi/music-auto_tagging-keras#6]
Hi Keunwoo,

This project is great. Thanks for making it reproducible.

What is the best way to train this network to reproduce the results?

What type of GPU's and how many do you recommend to avoid overfitting?

Many thanks,

Nicc

**Comment by keunwoochoi** [comment]
Hi, ah, there's no single best way I guess. I used one Titan X.
