### ISSUE TITLE
parameter problem

### ISSUE THREAD

**Issue by gongqiang** [keunwoochoi/music-auto_tagging-keras#7]
the input is 96X1366, and as we multiply all the pooling param in that dimension, we get:
  96=2x2x2x3x4， but in another dimension it doesn't fit at all: 4x4x4x5x4=1280，shouldn't it be1366？

**Comment by keunwoochoi** [comment]
You're correct. A better way would be either used shorter clips from the beginning - or pad zeros to use all 1366 frames. The current setting is chosen just because it was convenient to do so.

**Comment by gongqiang** [comment]
Thanks~

**Comment by somgist** [comment]
title : FCN-4 Convolve problem
hello my friends ,i am beginner and i have problem with convolve operation in FCN-4 in AUTOMATIC TAGGING USING DEEP CONVOLUTIONAL  NEURAL NETWORKS (table1 page 3 -
![image](https://user-images.githubusercontent.com/17214905/62132106-ab298c00-b2f1-11e9-97b3-ef53671f18b7.png  )
  )
i calculate output like below :
conv 3*3*kernel_size reduce the input dimention 2 unit.
for example (250*250*3) with conv(3*3*3) output is (250-2=248 , 250-2=248, 3)

i attach my caculation file below,
![image](https://user-images.githubusercontent.com/17214905/62132735-db255f00-b2f2-11e9-9640-4c2bca947727.png)

please help, thanks alot
